Add preview API key
Kentico/kontent-sample-app-graphql-react pull request #21
Opened 2021-12-08 15:05 UTC by winklertomas

### Motivation

Possibility to get unpublished content

### Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

Try to get unpublished content

2021-12-09 10:33 UTC, Simply007 requested changes
Just the extended preview information on Readme.

2021-12-09 10:33 UTC, Simply007 commented on README.md
> +| REACT_APP_KONTENT_PREVIEW_API_KEY  |    NO    | Preview API key to retrieve unpublished content                                          |
```suggestion
| REACT_APP_KONTENT_PREVIEW_API_KEY  |    NO    | Preview API key to retrieve unpublished content. If set, the application is fetching unpublished content, if not published content is being fetched.                                      |
```

2021-12-09 15:00 UTC, winklertomas commented
Thanks for the review -> will be merged after the release

2021-12-16 11:48 UTC, Simply007 approved these changes
OK

2021-12-16 15:31 UTC, merged